substitutions:
  name: zehnder-comfoair-can
  filter_time: 5s
  filter_send_every: '1'
  filter_window_size: '3'
  can_cs_pin: GPIO15

packages:
  remote_package:
    url: https://github.com/martkolt/zehnder-comfoair-can
    ref: main
    files:
      - packages/canbus.yml
      - packages/binary_sensors.yml
      - packages/button.yml
      - packages/select.yml
      - packages/sensors.yml
      - packages/switch.yml
      - packages/text_sensors.yml
      - packages/fan.yml
      - packages/climate.yml
      - packages/diagnostics.yml

esphome:
  name: ${name}
  friendly_name: Zehnder ComfoAir CAN
  comment: Zehnder ComfoAir Q450
  min_version: '2025.11.0'

esp8266:
  board: nodemcuv3
  framework:
    version: recommended

# Enable logging
logger:
  level: INFO
  logs:
    canbus: INFO

external_components:
  - components: [zehnder_comfoair_q]
    source: github://martkolt/zehnder-comfoair-can
    # source: components

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids: [16, 49, 54, 55, 65, 66, 67, 81, 82,
    117, 118, 119, 120, 121, 122, 128, 129, 130, 144, 145, 146, 192,
    209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220, 221, 227,
    274, 275, 276, 277, 278, 290, 291, 292, 293, 294]

###### Replace remianing with values from original yaml

# Enable Home Assistant API
api:
  encryption:
    key: ""

# Allow Over-The-Air updates
ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}-fallback"
    password: !secret fallback_hotspot_password

captive_portal:


